Repository code-words/codewords-ui, pull requests merged in 2019-07, with the labels that each got.

#4 Gameboard
  .gitignore
  src/components/AgentInput/index.js
  src/components/App/index.js
  src/components/Board/Board.test.js
  src/components/Board/_Board.scss
  src/components/Board/index.js
  src/components/Header/_Header.scss
  src/components/Header/index.js
  src/components/Main/_Main.scss
  src/components/Main/index.js
  src/index.js
  src/mock/mockData.js
  src/scss/index.scss
  src/scss/normalize.scss
  src/scss/variables.scss
Labels: enhancement, good first issue

#7 User input
  package-lock.json
  public/index.html
  src/components/AgentInput/_AgentInput.scss
  src/components/AgentInput/index.js
  src/components/App/_App.scss
  src/components/App/index.js
  src/components/Board/_Board.scss
  src/components/Board/index.js
  src/components/ConversationsList/index.js
  src/components/Header/_Header.scss
  src/components/Header/index.js
  src/components/Main/_Main.scss
  src/components/Main/index.js
  src/components/Score/_Score.scss
  src/mock/mockData.js
  src/scss/index.scss
  src/scss/variables.scss
Labels: enhancement, styling

#8 Startscreen routes
  .travis.yml
  package-lock.json
  src/components/App/index.js
  src/components/Header/index.js
  src/components/JoinGame/JoinGame.test.js
  src/components/JoinGame/_JoinGame.scss
  src/components/JoinGame/index.js
  src/components/Lobby/Lobby.test.js
  src/components/Lobby/_Lobby.scss
  src/components/Lobby/index.js
  src/components/NewGame/NewGame.test.js
  src/components/NewGame/_NewGame.scss
  src/components/NewGame/index.js
  src/components/RuleList/RuleList.test.js
  src/components/RuleList/_RuleList.scss
  src/components/RuleList/index.js
  src/components/StartScreen/StartScreen.test.js
  src/components/StartScreen/_StartScreen.scss
  src/components/StartScreen/index.js
  src/mock/mockData.js
  src/scss/index.scss
Labels: MVP, enhancement, good first issue

#18 Start building Lobby file
  src/components/Lobby/_Lobby.scss
  src/components/Lobby/index.js
Labels: MVP, enhancement, good first issue

#26 Experimental
  public/index.html
  src/components/Header/_Header.scss
  src/components/Header/index.js
  src/components/Lobby/_Lobby.scss
  src/components/Lobby/index.js
  src/scss/variables.scss
Labels: enhancement, styling

#25 Created and styled Lobby component
  src/components/Lobby/_Lobby.scss
  src/components/Lobby/index.js
  src/scss/variables.scss
Labels: MVP, enhancement, good first issue

#30 Start cable
  src/components/App/index.js
  src/components/JoinGame/index.js
  src/components/NewGame/index.js
Labels: Front-End, documentation, question

#32 Rebaser
  src/components/App/index.js
  src/components/Main/AgentInput/index.js
Labels: Front-End, duplicate, enhancement

#42 Lobby data
  src/components/App/index.js
  src/components/JoinGame/index.js
  src/components/NewGame/index.js
Labels: Front-End, good first issue

#51 Merger
  package-lock.json
  package.json
  src/components/App/index.js
  src/components/Header/index.js
  src/components/Lobby/_Lobby.scss
  src/components/Lobby/index.js
  src/components/Main/AgentInput/index.js
  src/components/Main/Board/_Board.scss
  src/components/Main/Board/index.js
  src/components/NewGame/index.js
Labels: Front-End, MVP, enhancement, good first issue, styling

#59 Intel input
  src/components/App/index.js
  src/components/Main/AgentInput/index.js
  src/components/Main/Board/index.js
  src/components/Main/index.js
Labels: Front-End, good first issue

#61 Test start flow
  package-lock.json
  package.json
  src/components/App/index.js
  src/components/JoinGame/index.test.js
  src/components/Lobby/__snapshots__/index.test.js.snap
  src/components/Lobby/index.js
  src/components/Lobby/index.test.js
  src/components/Main/AgentInput/index.js
  src/components/Main/index.js
  src/components/NewGame/index.js
  src/components/NewGame/index.test.js
Labels: Front-End, MVP, good first issue

#60 WIP: Force conditional render of active player/ agent input
  src/components/App/index.js
  src/components/Main/AgentInput/index.js
  src/components/Main/index.js
Labels: Front-End, bug, help wanted

#66 Hint flow
  src/components/App/index.js
  src/components/Main/AgentInput/index.js
  src/components/Main/Board/Card/index.js
  src/components/Main/index.js
  src/images/blue.jpg
  src/images/bystander.jpg
  src/images/red.jpg
Labels: Front-End, enhancement, good first issue

#68 Sending hint, still need to Receive hint
  src/components/App/index.js
  src/components/Main/Board/Card/index.js
Labels: Front-End, MVP

#69 Hint flow
  src/components/App/index.js
  src/components/Main/AgentHUD/_AgentHUD.scss
  src/components/Main/AgentHUD/index.js
  src/components/Main/AgentHUD/index.test.js
  src/components/Main/AgentInput/index.js
  src/components/Main/index.js
Labels: Front-End, MVP, good first issue

#79 Loose ends
  src/components/App/index.js
  src/components/ConfDialog/_ConfDialog.scss
  src/components/ConfDialog/index.js
  src/components/Lobby/_Lobby.scss
  src/components/Lobby/index.js
  src/components/Main/AgentHUD/_AgentHUD.scss
  src/components/Main/AgentHUD/index.js
  src/components/Main/AgentInput/_AgentInput.scss
  src/components/Main/AgentInput/index.js
  src/components/Main/Board/Card/_Card.scss
  src/components/Main/Board/Card/index.js
  src/components/Main/Board/_Board.scss
  src/components/Main/Board/index.js
  src/components/Main/index.js
  src/images/blue.jpg
  src/images/bystander.jpg
  src/images/red.jpg
  src/scss/index.scss
Labels: Front-End, MVP, enhancement

#90 Switch server host based on client window.location
  src/variables/index.js
Labels: Front-End

#92 Fix: Set server host per environment
  src/variables/index.js
Labels: Front-End

#95 Render marker and styling based on who is active, across clients
  src/components/App/index.js
  src/components/Main/Score/_Score.scss
  src/components/Main/Score/index.js
  src/components/Main/index.js
Labels: Front-End, enhancement, nice to have

#115 Agent hud pass extra guess
  src/components/App/index.js
  src/components/Main/AgentHUD/_AgentHUD.scss
  src/components/Main/AgentHUD/index.js
  src/components/Main/index.js
Labels: BugFIX, Front-End, MVP

#116 Add Travis CI build status to README
  README.md
Labels: Front-End, documentation
